// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Liveness check used to verify the IPC pipeline round-trips. */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**
	 *  List a directory into a structured [`DirListing`] (utility; panels use the
	 *  stateful commands below).
	 */
	listDir: (path: string, showHidden: boolean) => __TAURI_INVOKE<DirListing>("list_dir", { path, showHidden }),
	/**  Return the current configuration (Phase 1: defaults). */
	getConfig: () => __TAURI_INVOKE<Config>("get_config"),
	/**
	 *  The active keymap (action id → key chords), sourced from core config so the
	 *  webview never hardcodes keys (SPEC §6).
	 */
	getKeymap: () => __TAURI_INVOKE<KeyBinding[]>("get_keymap"),
	/**  Populate both panels with their starting directory (home). Call once on boot. */
	init: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("init")),
	/**
	 *  Report a panel's rendered layout so the cursor state machine can compute the
	 *  column/page traversal (SPEC §5.2).
	 */
	setViewport: (panel: PanelId, columns: number, rows: number) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_viewport", { panel, columns, rows })),
	/**  Apply a cursor motion (SPEC §5.2). Pure and instant — runs synchronously. */
	moveCursor: (panel: PanelId, motion: Motion) => typedError<AppSnapshot, string>(__TAURI_INVOKE("move_cursor", { panel, motion })),
	/**  Set the active (focused) panel (SPEC §5.1). */
	setActivePanel: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_active_panel", { panel })),
	/**  Toggle selection of the entry under the cursor (Space). `..` is a no-op. */
	toggleSelection: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("toggle_selection", { panel })),
	/**  Additively select the entry under the cursor, then move (Shift+Arrow). */
	selectAndMove: (panel: PanelId, motion: Motion) => typedError<AppSnapshot, string>(__TAURI_INVOKE("select_and_move", { panel, motion })),
	/**  Select all selectable entries in the panel (`*`). */
	selectAll: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("select_all", { panel })),
	/**  Clear the panel's selection (`-`). */
	deselectAll: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("deselect_all", { panel })),
	/**
	 *  Navigate a panel: into the entry under the cursor, up to the parent (with the
	 *  auto-position-on-exited-folder rule, §5.2), or to an explicit path.
	 */
	navigate: (panel: PanelId, target: NavTarget) => typedError<AppSnapshot, string>(__TAURI_INVOKE("navigate", { panel, target })),
	/**
	 *  Re-read a panel's current directory, keeping the cursor on the same entry name
	 *  when it still exists (graceful refresh, SPEC §5.6).
	 */
	refresh: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("refresh", { panel })),
};

/** Events */
export const events = {
	configChangedEvent: makeEvent<ConfigChangedEvent>("config-changed-event"),
	opCollisionEvent: makeEvent<OpCollisionEvent>("op-collision-event"),
	opCompleteEvent: makeEvent<OpCompleteEvent>("op-complete-event"),
	opErrorEvent: makeEvent<OpErrorEvent>("op-error-event"),
	opProgressEvent: makeEvent<OpProgressEvent>("op-progress-event"),
	panelChangedEvent: makeEvent<PanelChangedEvent>("panel-changed-event"),
};

/* Types */
/**
 *  A full snapshot of navigation state — both panels plus which is active. Every
 *  navigation command returns this so the frontend replaces its whole render
 *  state in one step (panels are small; cloning is cheap).
 */
export type AppSnapshot = {
	left: PanelState,
	right: PanelState,
	active: PanelId,
};

/**
 *  Payload for the collision-prompt event. `multiple` enables the `*_all`
 *  resolution choices in the dialog (§5.4a).
 */
export type CollisionPrompt = {
	op_id: string,
	path: string,
	multiple: boolean,
};

/**
 *  Root config document (serialized to TOML). Ships with working defaults — the
 *  app is fully usable with zero configuration (§7).
 * 
 *  Keybindings and the file-type→application map are deliberately omitted from
 *  the scaffold so we don't freeze an unreviewed schema; they join here with
 *  feature work.
 */
export type Config = {
	left_panel: PanelPrefs,
	right_panel: PanelPrefs,
	/**  Global "Move to Trash" default — OFF by default, persisted (§5.4a). */
	trash_default: boolean,
	/**  Id of the active theme. */
	theme: string,
};

/**  Config was reloaded (hot reload — nice-to-have). No payload. */
export type ConfigChangedEvent = null;

/**
 *  Result of reading a directory. Unreadable entries appear in `entries` carrying
 *  a non-`Ok` [`EntryMarker`] rather than aborting the listing (§5.6).
 */
export type DirListing = {
	path: string,
	entries: Entry[],
};

/**  One row in a directory listing. */
export type Entry = {
	name: string,
	kind: EntryKind,
	size: number,
	/**  Modification time, Unix seconds. */
	modified: number,
	/**  POSIX permission bits (e.g. `0o755`). */
	permissions: number,
	/**  Target path when `kind == Symlink`; `None` otherwise. */
	symlink_target: string | null,
	is_executable: boolean,
	marker: EntryMarker,
};

/**  What kind of filesystem object an entry is. */
export type EntryKind = "file" | "dir" | "symlink" | "special";

/**
 *  Readability marker, so a single unreadable entry renders as a marker rather
 *  than failing the whole listing (§5.6).
 */
export type EntryMarker = "ok" | "denied" | "broken";

/**
 *  One keybinding: an action id (e.g. `"cursor.down"`) and the key chords bound
 *  to it. Sourced from core config so the webview never hardcodes keys (§6/§7).
 *  Remapping, persistence, and conflict detection are a later slice.
 */
export type KeyBinding = {
	action: string,
	keys: string[],
};

/**
 *  Cursor motions — the intents the frontend forwards; the core turns them into
 *  a new cursor index via the single traversal state machine (§5.2).
 */
export type Motion = "up" | "down" | "left" | "right" | "page_up" | "page_down" | "home" | "end";

/**  Target for `navigate`. */
export type NavTarget = 
/**  Enter the directory currently under the cursor. */
{ kind: "into" } | 
/**  Go to the parent, auto-positioning on the folder just exited (§5.2). */
{ kind: "parent" } | 
/**  Jump to an explicit path (absolute or relative). */
{ kind: "path"; value: string };

/**  A name collision needs a user decision (FAR dialog shapes). */
export type OpCollisionEvent = CollisionPrompt;

/**  An operation finished (success / partial / failed). */
export type OpCompleteEvent = OpOutcome;

/**  An operation failed — rendered as a red-background dialog. */
export type OpErrorEvent = OpErrorInfo;

/**
 *  Payload for the failure event — the frontend renders this as a red-background
 *  dialog. `offer_elevate` gates the OS-native elevation choice (§5.4b / §5.6).
 */
export type OpErrorInfo = {
	op_id: string,
	path: string,
	reason: string,
	offer_elevate: boolean,
};

/**
 *  Structured result of an operation — the frontend renders this, never an
 *  opaque thrown error (§5.6).
 */
export type OpOutcome = {
	op_id: string,
	status: OpStatus,
	summary: string,
};

/**  Progress event payload for a running operation (§5.4a). */
export type OpProgress = {
	op_id: string,
	bytes_done: number,
	bytes_total: number,
	count_done: number,
	count_total: number,
	/**  The file currently being processed. */
	current: string,
};

/**  Progress tick for a running operation. */
export type OpProgressEvent = OpProgress;

/**  Terminal status of an operation (§5.4a / §5.6). */
export type OpStatus = "pending" | "success" | "partial" | "failed";

/**
 *  Payload for a panel-state change pushed by the core, e.g. the directory
 *  changed underneath us and was refreshed (§5.6).
 */
export type PanelChanged = {
	panel: PanelId,
	state: PanelState,
};

/**  A panel's state changed out of band (e.g. directory changed underneath us). */
export type PanelChangedEvent = PanelChanged;

/**
 *  Layout geometry reported by the frontend on resize / view-mode change. The
 *  cursor state machine needs it to compute the column/page traversal (§5.2) —
 *  the frontend owns pixels, the core owns the resulting cursor index.
 */
export type PanelGeometry = {
	columns: number,
	rows_per_column: number,
};

/**  Which panel an intent targets. The two-panel model is the app's core (§5.1). */
export type PanelId = "left" | "right";

/**  Persisted per-panel preferences, restored on the next launch (§5.8 / §7). */
export type PanelPrefs = {
	/**  Directory the panel opens to; `None` means a sensible default (e.g. home). */
	start_dir: string | null,
	view_mode: ViewMode,
	sort_mode: SortMode,
	show_hidden: boolean,
};

/**  The full state of one panel — the unit the frontend renders. */
export type PanelState = {
	path: string,
	entries: Entry[],
	/**  Index into `entries` of the entry under the cursor. */
	cursor_index: number,
	/**  Indices of selected entries (§5.3). Persists across cursor movement. */
	selection: number[],
	view_mode: ViewMode,
	sort_mode: SortMode,
	show_hidden: boolean,
	geometry: PanelGeometry,
};

/**  Sort order. Folders-first-by-name is the default (§5.8). */
export type SortMode = "name_folders_first" | "type_name" | "size" | "date";

/**
 *  Per-panel view mode. `Columns(n)` covers the brief multi-column modes
 *  (2 by default); `Detailed` is the single-column-with-metadata mode (§5.2).
 */
export type ViewMode = { kind: "columns"; columns: number } | { kind: "detailed" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

