// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Liveness check used to verify the IPC pipeline round-trips. */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**
	 *  List a directory into a structured [`DirListing`] (utility; panels use the
	 *  stateful commands below).
	 */
	listDir: (path: string, showHidden: boolean, sort: SortMode) => __TAURI_INVOKE<DirListing>("list_dir", { path, showHidden, sort }),
	/**  Return the configuration currently in effect (loaded from TOML at `init`, §7). */
	getConfig: () => typedError<Config, string>(__TAURI_INVOKE("get_config")),
	/**
	 *  The active keymap (action id → key chords), sourced from core config so the
	 *  webview never hardcodes keys (SPEC §6).
	 */
	getKeymap: () => __TAURI_INVOKE<KeyBinding[]>("get_keymap"),
	/**
	 *  The F1 help book, filtered by `query` (§6). Both the content and the search
	 *  matching are the core's: this only supplies the packaging metadata, which is
	 *  the one thing `fm-core` cannot know about itself.
	 * 
	 *  `package_info()` resolves to the bundle's `productName` from `tauri.conf.json`
	 *  and its `version` — which, since `tauri.conf.json` omits `version`, the
	 *  bundler takes from `Cargo.toml`, making the workspace manifest the single
	 *  source of truth. The remaining fields come straight from that same manifest,
	 *  so there is no hand-maintained copy of any of this to drift.
	 */
	getHelp: (query: string) => __TAURI_INVOKE<HelpBook>("get_help", { query }),
	/**
	 *  Open one of the About topic's links in the user's browser (§6).
	 * 
	 *  Restricted to `http`/`https` on purpose. The webview only ever passes URLs the
	 *  core just handed it, but this command is reachable from any frontend code, and
	 *  the opener plugin will happily launch `file://` paths or custom schemes —
	 *  which is a local-file-execution primitive, not a browser link. Narrowing the
	 *  scheme here keeps that door shut regardless of what the renderer does.
	 */
	openLink: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_link", { url })),
	/**
	 *  Ask the update feed whether a newer release exists (§ release process).
	 * 
	 *  `Ok(None)` means "up to date" *and* "could not tell" — the two are
	 *  deliberately not distinguished. This runs unprompted at startup, and a laptop
	 *  that is offline, behind a captive portal, or simply ahead of a not-yet-created
	 *  release must not produce an error the user has to dismiss. Real failures are
	 *  still worth seeing while developing, so they are logged.
	 * 
	 *  Updates are verified against the public key in `tauri.conf.json` before
	 *  anything is written to disk; an unsigned or mis-signed payload fails here
	 *  rather than being installed.
	 */
	checkUpdate: () => typedError<{
	version: string,
	/**  Release notes from the feed. Often empty; the renderer must cope. */
	notes: string,
} | null, string>(__TAURI_INVOKE("check_update")),
	/**
	 *  Download, verify, install the pending update, then relaunch into it.
	 * 
	 *  Unlike [`check_update`] this is user-initiated, so failures are surfaced: the
	 *  user pressed a button and is owed an answer. Does not return on success — the
	 *  process is replaced by the new build.
	 */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	/**
	 *  Load the persisted configuration and populate both panels from it — each panel
	 *  reopens its last directory with its own view/sort/hidden state (§5.8 / §7),
	 *  falling back to home when a remembered directory is gone. Call once on boot.
	 */
	init: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("init")),
	/**
	 *  Report a panel's rendered layout so the cursor state machine can compute the
	 *  column/page traversal (SPEC §5.2).
	 */
	setViewport: (panel: PanelId, columns: number, rows: number) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_viewport", { panel, columns, rows })),
	/**  Apply a cursor motion (SPEC §5.2). Pure and instant — runs synchronously. */
	moveCursor: (panel: PanelId, motion: Motion) => typedError<AppSnapshot, string>(__TAURI_INVOKE("move_cursor", { panel, motion })),
	/**
	 *  Move a panel's cursor to an explicit entry index (SPEC §5.2). Backs mouse-click
	 *  focus: the frontend reports the clicked entry's global index; the core clamps
	 *  and owns the resulting cursor position. Pure and instant — runs synchronously.
	 */
	setCursor: (panel: PanelId, index: number) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_cursor", { panel, index })),
	/**  Set the active (focused) panel (SPEC §5.1). */
	setActivePanel: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_active_panel", { panel })),
	/**
	 *  Set a panel's view mode — 1/2/3-column brief or the detailed single-column
	 *  mode. Pure layout: no directory re-read is needed, only the cursor geometry
	 *  the frontend re-reports afterwards. Persisted per panel.
	 */
	setViewMode: (panel: PanelId, mode: ViewMode) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_view_mode", { panel, mode })),
	/**
	 *  Set a panel's sort mode (§5.8). Re-sorts the entries already loaded — no I/O —
	 *  keeping the cursor and selection on the same entries. Persisted per panel.
	 */
	setSortMode: (panel: PanelId, mode: SortMode) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_sort_mode", { panel, mode })),
	/**
	 *  Show or hide dotfiles in a panel (§5.8 — shown by default). Needs a re-read,
	 *  which runs off the state lock; the cursor and selection survive by name.
	 *  Persisted per panel.
	 */
	setShowHidden: (panel: PanelId, value: boolean) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_show_hidden", { panel, value })),
	/**  Toggle selection of the entry under the cursor (Space). `..` is a no-op. */
	toggleSelection: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("toggle_selection", { panel })),
	/**
	 *  Move the cursor, flipping the selection of every entry it sweeps over
	 *  (Shift+Arrow / PageUp / PageDown / Home / End). The entry the cursor leaves is
	 *  flipped, the one it lands on is not, so repeated presses paint a continuous run.
	 */
	selectAndMove: (panel: PanelId, motion: Motion) => typedError<AppSnapshot, string>(__TAURI_INVOKE("select_and_move", { panel, motion })),
	/**  Select all selectable entries in the panel (`*`). */
	selectAll: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("select_all", { panel })),
	/**  Clear the panel's selection (`-`). */
	deselectAll: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("deselect_all", { panel })),
	/**
	 *  Navigate a panel: into the entry under the cursor, up to the parent (with the
	 *  auto-position-on-exited-folder rule, §5.2), or to an explicit path.
	 */
	navigate: (panel: PanelId, target: NavTarget) => typedError<AppSnapshot, string>(__TAURI_INVOKE("navigate", { panel, target })),
	/**
	 *  Show the active panel's folder on the other panel too (Ctrl+=).
	 * 
	 *  A push, not a Tab: only the passive panel moves, so the keyboard stays where
	 *  the user left it. Delegating to [`navigate`] rather than listing here is what
	 *  keeps the watcher re-armed, the new directory persisted, and the cursor rules
	 *  identical to every other directory change — the same reason `terminal_run`'s
	 *  `cd` arm delegates.
	 */
	equalizePanels: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("equalize_panels")),
	/**
	 *  Re-read a panel's current directory, keeping the cursor on the same entry name
	 *  when it still exists (graceful refresh, SPEC §5.6).
	 */
	refresh: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("refresh", { panel })),
	/**  Cmd+F — open a fresh search box on the panel. The cursor does not move. */
	searchStart: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("search_start", { panel })),
	/**
	 *  Append typed text to the query and jump the cursor to the first match. A
	 *  character matching nothing is rejected and bumps `search.miss_rev` instead,
	 *  which is the frontend's cue to beep.
	 * 
	 *  Takes a `String` rather than a `char`: it marshals cleanly through specta, and
	 *  a paste into the box later needs no second command.
	 */
	searchPush: (panel: PanelId, text: string) => typedError<AppSnapshot, string>(__TAURI_INVOKE("search_push", { panel, text })),
	/**  Backspace — drop the last character and let the cursor follow it back. */
	searchBackspace: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("search_backspace", { panel })),
	/**  Esc, Enter, or the box's ✕ — close it, leaving the cursor on the match. */
	searchClose: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("search_close", { panel })),
	/**
	 *  Create a directory named `name` inside `panel`'s current directory (F7), then
	 *  re-read the listing and position the cursor on the new folder. `name` may be a
	 *  nested relative path (`a/b`), in which case the cursor lands on the first
	 *  component.
	 */
	createDir: (panel: PanelId, name: string) => typedError<AppSnapshot, string>(__TAURI_INVOKE("create_dir", { panel, name })),
	/**
	 *  Rename the entry under `panel`'s cursor to `new_name`, in place (Shift+F6).
	 *  Errors if the cursor is on `..`, `new_name` is empty / contains a separator, or
	 *  a file of that name already exists (never silently overwrites, §5.4a). On
	 *  success, re-reads the listing and keeps the cursor on the renamed entry.
	 */
	rename: (panel: PanelId, newName: string) => typedError<AppSnapshot, string>(__TAURI_INVOKE("rename", { panel, newName })),
	/**
	 *  Recursively compute the size of each folder in `paths` and cache the results,
	 *  then return a fresh snapshot with the computed sizes surfaced onto the
	 *  matching dir entries (`computed_size`). This always recomputes the requested
	 *  paths — pressing F3 again is the explicit "recalculate" gesture.
	 * 
	 *  The walk runs on the blocking thread pool and never holds the state lock, so
	 *  large trees never block the UI (§5.4a). Infinite recursion is prevented by
	 *  [`fm_core::fs::dir_size`] (symlinks are never followed).
	 */
	calculateDirSize: (paths: string[]) => typedError<AppSnapshot, string>(__TAURI_INVOKE("calculate_dir_size", { paths })),
	/**
	 *  Set the global "Move to Trash" default (the delete-dialog checkbox), OFF by
	 *  default and persisted across sessions (§5.4a).
	 */
	setTrashDefault: (value: boolean) => typedError<AppSnapshot, string>(__TAURI_INVOKE("set_trash_default", { value })),
	/**
	 *  Begin a copy (F5) or move (F6) of the active panel's selection — or, when
	 *  nothing is selected, the entry under the cursor (never `..`). `dest` is the
	 *  editable destination from the F5/F6 prompt; it accepts `..`, relative, and
	 *  absolute paths, resolved against the active panel's directory (§5.4a).
	 * 
	 *  Registers the op, spawns the transfer on a background thread (never blocking
	 *  the UI), and returns the `op_id` the frontend uses to correlate the progress /
	 *  collision / error / complete events and to cancel.
	 */
	startTransfer: (kind: OpKind, dest: string) => typedError<string, string>(__TAURI_INVOKE("start_transfer", { kind, dest })),
	/**
	 *  Begin a delete (F8) of the active panel's selection — or, when nothing is
	 *  selected, the entry under the cursor (never `..`). Reads the persisted
	 *  "Move to Trash" flag from state; when set, items go to the OS trash, otherwise
	 *  they are permanently removed (§5.4a). Mirrors [`start_transfer`]: registers the
	 *  op, spawns the delete on a background thread (never blocking the UI), and
	 *  returns the `op_id` the frontend uses to correlate progress / error / complete
	 *  events and to cancel.
	 */
	startDelete: () => typedError<string, string>(__TAURI_INVOKE("start_delete")),
	/**  Answer a collision prompt for a running op (§5.4a). */
	resolveCollision: (opId: string, resolution: Resolution) => typedError<null, string>(__TAURI_INVOKE("resolve_collision", { opId, resolution })),
	/**
	 *  Answer an error prompt for a running op — Retry / Skip / Skip All / Cancel /
	 *  Elevate (§5.6).
	 */
	resolveError: (opId: string, resolution: ErrorResolution) => typedError<null, string>(__TAURI_INVOKE("resolve_error", { opId, resolution })),
	/**  Request cancellation of a running op; the engine stops between items (§5.4a). */
	cancelOp: (opId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_op", { opId })),
	/**
	 *  Open the entry under `panel`'s cursor. `Open` (Enter) uses the system default
	 *  and *runs* executables; `View` (F3) / `Edit` (F4) route to the embedded viewer
	 *  or editor, or to a configured external tool (§5.5).
	 * 
	 *  The core (`fm_core::open::plan_open`) sniffs the file and makes the whole
	 *  decision; this handler only performs the side-effect it asks for and returns
	 *  whatever the frontend needs to render (SPEC §3).
	 */
	openEntry: (panel: PanelId, action: OpenAction) => typedError<OpenOutcome, string>(__TAURI_INVOKE("open_entry", { panel, action })),
	/**
	 *  Cmd+T: move the keyboard to the prompt, or hand it back to the panel that is
	 *  still marked active (§5.7).
	 */
	terminalToggleFocus: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_toggle_focus")),
	/**
	 *  Cmd+Shift+T: expand the pane to the bottom half of the window, or collapse it
	 *  back to the bare command line (§5.7).
	 */
	terminalToggleHalf: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_toggle_half")),
	/**  Esc: draw the panels aside to reveal the full terminal, and back (§6). */
	terminalToggleCurtain: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_toggle_curtain")),
	/**
	 *  Mirror the text being typed at the prompt. Returns nothing: this is an echo
	 *  of what the frontend already shows, and re-rendering from it would fight the
	 *  caret (see `TerminalState::input_rev`).
	 */
	terminalSetInput: (text: string) => typedError<null, string>(__TAURI_INVOKE("terminal_set_input", { text })),
	/**
	 *  Enter at the prompt. The core decides what the line means; a `cd` becomes a
	 *  panel navigation, `clear` empties the buffer, and anything else is spawned.
	 */
	terminalRun: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_run")),
	/**
	 *  Ctrl+C: interrupt the running command, or — with nothing running — clear the
	 *  prompt (§5.7).
	 */
	terminalInterruptOrClear: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_interrupt_or_clear")),
	/**  Up / Down at the prompt: recall a previous command (§5.7). */
	terminalHistory: (dir: HistoryDir) => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_history", { dir })),
	/**
	 *  Ctrl+Enter: append the name under `panel`'s cursor to the command line,
	 *  shell-quoted, without the panel losing focus (§5.7).
	 */
	terminalInsertName: (panel: PanelId) => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_insert_name", { panel })),
	/**
	 *  Re-cap the scrollback from the control in the corner of the expanded pane,
	 *  and persist the choice (§5.7 / §7).
	 */
	terminalSetScrollback: (bytes: number) => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_set_scrollback", { bytes })),
	/**  Empty the scrollback (Ctrl+L, or the button in the corner). */
	terminalClearBuffer: () => typedError<AppSnapshot, string>(__TAURI_INVOKE("terminal_clear_buffer")),
	/**
	 *  The whole scrollback, for the frontend's initial sync and any re-sync (on
	 *  expand, or after the cap changes).
	 */
	terminalBuffer: () => typedError<TerminalBuffer, string>(__TAURI_INVOKE("terminal_buffer")),
	/**
	 *  Report the viewer's visible geometry in rows and characters, the same way the
	 *  panels report theirs: the frontend owns pixels, the core owns what they mean.
	 */
	viewSetViewport: (id: string, rows: number, cols: number) => typedError<ViewPage, string>(__TAURI_INVOKE("view_set_viewport", { id, rows, cols })),
	viewScroll: (id: string, motion: ViewMotion) => typedError<ViewPage, string>(__TAURI_INVOKE("view_scroll", { id, motion })),
	/**  Toggle between text and hex (F4), keeping the byte position. */
	viewToggleHex: (id: string) => typedError<ViewPage, string>(__TAURI_INVOKE("view_toggle_hex", { id })),
	/**
	 *  Toggle word wrap (F2) and persist it, the way the panels persist their view
	 *  state (§5.8).
	 */
	viewSetWrap: (id: string, wrap: boolean) => typedError<ViewPage, string>(__TAURI_INVOKE("view_set_wrap", { id, wrap })),
	/**
	 *  Search from just past the current position (F7 / Shift+F7). `Ok(None)` means
	 *  "not found" — a normal outcome the frontend reports in the status line,
	 *  rather than an error dialog.
	 */
	viewSearch: (id: string, needle: string, direction: SearchDirection) => typedError<{
	id: string,
	path: string,
	name: string,
	mode: ViewerMode,
	wrap: boolean,
	encoding: TextEncoding,
	/**  Line numbers (text) or byte offsets (hex), one per row. */
	gutter: string[],
	rows: string[],
	top_offset: number,
	total_bytes: number,
	/**  Position through the file, 0–100, from `top_offset`. */
	percent: number,
	/**
	 *  1-based logical line at the top of the window, when the index reaches
	 *  that far; `None` in hex mode.
	 */
	top_line: number | null,
	/**  Horizontal scroll, in characters, when wrapping is off. */
	col_offset: number,
	/**
	 *  Whether the file could be written — drives the status line's read-only
	 *  marker and whether F6 (view → edit) can offer an editable buffer.
	 */
	writable: boolean,
} | null, string>(__TAURI_INVOKE("view_search", { id, needle, direction })),
	/**  Jump to a line, byte offset, or percentage through the file (F5). */
	viewGoto: (id: string, target: GotoTarget) => typedError<ViewPage, string>(__TAURI_INVOKE("view_goto", { id, target })),
	/**
	 *  Hand the file open in the viewer to the editor (F6). The path comes from the
	 *  session rather than the frontend, so the webview never names the file it
	 *  wants opened for writing.
	 */
	viewToEdit: (id: string) => typedError<EditDoc, string>(__TAURI_INVOKE("view_to_edit", { id })),
	viewClose: (id: string) => typedError<null, string>(__TAURI_INVOKE("view_close", { id })),
	/**
	 *  Write the buffer back (`editor.save`). `force` answers a previous `Conflict`
	 *  outcome with "overwrite anyway". The outcome is structured, never a thrown
	 *  error (§5.6).
	 */
	editSave: (id: string, text: string, force: boolean) => typedError<SaveOutcome, string>(__TAURI_INVOKE("edit_save", { id, text, force })),
	/**  Drop back from the editor to the viewer on the same file (F6). */
	editToView: (id: string) => typedError<ViewPage, string>(__TAURI_INVOKE("edit_to_view", { id })),
	editClose: (id: string) => typedError<null, string>(__TAURI_INVOKE("edit_close", { id })),
};

/** Events */
export const events = {
	configChangedEvent: makeEvent<ConfigChangedEvent>("config-changed-event"),
	opCollisionEvent: makeEvent<OpCollisionEvent>("op-collision-event"),
	opCompleteEvent: makeEvent<OpCompleteEvent>("op-complete-event"),
	opErrorEvent: makeEvent<OpErrorEvent>("op-error-event"),
	opProgressEvent: makeEvent<OpProgressEvent>("op-progress-event"),
	panelChangedEvent: makeEvent<PanelChangedEvent>("panel-changed-event"),
	terminalChunkEvent: makeEvent<TerminalChunkEvent>("terminal-chunk-event"),
	terminalStateEvent: makeEvent<TerminalStateEvent>("terminal-state-event"),
};

/* Types */
/**
 *  The About topic: who the app is, plus a few label/value facts and the
 *  project's outbound links.
 */
export type AboutBody = {
	app: AppInfo,
	lines: HelpLine[],
	/**
	 *  Rendered as activatable rows, separately from [`Self::lines`], so the
	 *  renderer never has to guess which values happen to be URLs. Already
	 *  filtered — an unset link is absent here, not empty.
	 */
	links: HelpLink[],
};

/**
 *  Who this app is, for the About topic. Filled in by the platform adapter from
 *  its packaging metadata (Cargo / the Tauri bundle config), because the core
 *  has no packaging of its own to read.
 */
export type AppInfo = {
	/**  Display name, e.g. `"dimnav"` — the product name, not the crate. */
	name: string,
	version: string,
	description: string,
	/**  SPDX identifier, e.g. `"MIT"`. */
	license: string,
	/**
	 *  Project website. Empty string when unset — the About topic omits the row
	 *  rather than rendering a dead link.
	 */
	homepage: string,
	/**  Source repository. Empty string when unset. */
	repository: string,
	/**  Where to support the project financially. Empty string when unset. */
	sponsor: string,
};

/**
 *  A full snapshot of navigation state — both panels plus which is active. Every
 *  navigation command returns this so the frontend replaces its whole render
 *  state in one step (panels are small; cloning is cheap).
 */
export type AppSnapshot = {
	left: PanelState,
	right: PanelState,
	active: PanelId,
	/**
	 *  Global "Move to Trash" default for the delete dialog, OFF by default
	 *  (§5.4a). The frontend renders the checkbox from this.
	 */
	trash_default: boolean,
	/**
	 *  The command line's state (§5.7). Rides along on every snapshot so the
	 *  terminal row re-renders in lockstep with the panels — in particular its
	 *  `cwd`, which follows the active panel.
	 */
	terminal: TerminalState,
};

/**
 *  Payload for the collision-prompt event. `multiple` enables the `*_all`
 *  resolution choices in the dialog (§5.4a).
 */
export type CollisionPrompt = {
	op_id: string,
	path: string,
	multiple: boolean,
};

/**
 *  Root config document (serialized to TOML). Ships with working defaults — the
 *  app is fully usable with zero configuration (§7).
 * 
 *  Field order matters: TOML rejects a plain value emitted after a table, so the
 *  scalars come first and the panel tables / association array-of-tables last.
 *  `serde(default)` means a partial or hand-edited file still loads.
 * 
 *  Keybindings are deliberately omitted so we don't freeze an unreviewed schema;
 *  they join here with the remapping slice.
 */
export type Config = {
	/**  Global "Move to Trash" default — OFF by default, persisted (§5.4a). */
	trash_default?: boolean,
	/**  Id of the active theme. */
	theme?: string,
	/**
	 *  Largest file the embedded editor will load. Above this, F4 hands off to
	 *  the external editor — the editor holds the whole document in memory,
	 *  unlike the viewer, which pages.
	 */
	edit_max_bytes?: number,
	left_panel?: PanelPrefs,
	right_panel?: PanelPrefs,
	viewer?: ViewerPrefs,
	terminal?: TerminalPrefs,
	watch?: WatchPrefs,
	/**
	 *  File-type → external-application map (§5.5). Empty by default, so every
	 *  file opens with the system default until the user edits the TOML.
	 * 
	 *  Stays **last**: it serializes as an array-of-tables, and TOML rejects any
	 *  plain value or table emitted after one.
	 */
	associations?: FileAssociation[],
};

/**  Config was reloaded (hot reload — nice-to-have). No payload. */
export type ConfigChangedEvent = null;

/**
 *  Result of reading a directory. Unreadable entries appear in `entries` carrying
 *  a non-`Ok` [`EntryMarker`] rather than aborting the listing (§5.6).
 */
export type DirListing = {
	path: string,
	entries: Entry[],
};

/**
 *  An open editor document. The core owns the document (path, encoding, line
 *  endings, permissions, on-disk identity); the frontend owns the editable text
 *  buffer and hands it back whole on save.
 */
export type EditDoc = {
	id: string,
	path: string,
	name: string,
	/**  Full text, decoded and normalized to `\n` line endings. */
	text: string,
	encoding: TextEncoding,
	eol: Eol,
	/**
	 *  True when the file is not writable — the editor reports this up front
	 *  rather than failing at write time.
	 */
	read_only: boolean,
};

/**  One row in a directory listing. */
export type Entry = {
	name: string,
	kind: EntryKind,
	size: number,
	/**  Modification time, Unix seconds. */
	modified: number,
	/**
	 *  Creation/birth time, Unix seconds; `0` when the platform/filesystem does
	 *  not report it.
	 */
	created: number,
	/**  POSIX permission bits (e.g. `0o755`). */
	permissions: number,
	/**  Numeric owner uid / group gid (0 on non-unix). */
	uid: number,
	gid: number,
	/**
	 *  Resolved owner / group names; `None` when unresolved (frontend then shows
	 *  the numeric id).
	 */
	owner: string | null,
	group: string | null,
	/**  Hardlink count (0 on non-unix). */
	nlink: number,
	/**  Target path when `kind == Symlink`; `None` otherwise. */
	symlink_target: string | null,
	/**
	 *  The raw POSIX fact: any of the three x bits is set. Note this is *not* the
	 *  same question as "may we run it" — see [`crate::filetype::is_runnable`].
	 */
	is_executable: boolean,
	/**  Which colour class this row falls into (§4). */
	category: EntryCategory,
	marker: EntryMarker,
	/**
	 *  Recursively computed folder size in bytes, when it has been calculated
	 *  (F3) and is present in the size cache; `None` otherwise. Always `None`
	 *  for non-directories.
	 */
	computed_size: number | null,
};

/**
 *  What a listing row *is*, for colouring and for the execute-vs-launch decision
 *  (§4). Derived from the name, kind and permission bits by
 *  [`crate::filetype::classify`] — never set by hand.
 */
export type EntryCategory = "dir" | "symlink" | 
/**
 *  A dotfile or dotfolder. Outranks `Dir`, so a hidden folder reads as
 *  hidden rather than as a folder.
 */
"hidden" | "doc" | "data" | "code" | "archive" | "image" | "media" | 
/**  Carries the exec bit *and* nothing about its name says otherwise. */
"exec" | 
/**  Nothing claimed it — renders in the default foreground colour. */
"plain";

/**  What kind of filesystem object an entry is. */
export type EntryKind = "file" | "dir" | "symlink" | "special";

/**
 *  Readability marker, so a single unreadable entry renders as a marker rather
 *  than failing the whole listing (§5.6).
 */
export type EntryMarker = "ok" | "denied" | "broken";

/**
 *  Line-ending style, detected from the file's first line break and re-applied
 *  on save so editing never rewrites every line of a CRLF file.
 */
export type Eol = "lf" | "crlf" | "cr";

/**
 *  Error-dialog resolution. Adds `Retry` and `Elevate`; elevation routes through
 *  the OS-native auth prompt on the Tauri side — the app never handles passwords
 *  (§5.6).
 */
export type ErrorResolution = "retry" | "skip" | "skip_all" | "cancel" | "elevate";

/**
 *  One file-type → handler mapping (§5.5 / §7). Associates a set of extensions
 *  with what should happen for each action. Matched case-insensitively on the
 *  entry's extension, no leading dot (e.g. `"md"`).
 * 
 *  Each value is a handler string, parsed by [`crate::open::Handler`]:
 *  `"internal"` (the embedded viewer/editor), `"system"` (the OS default app),
 *  or an application name (`"Visual Studio Code"`). `None` means "no opinion" —
 *  View/Edit then fall back to `open`, and finally to the built-in default for
 *  the file's detected type.
 */
export type FileAssociation = {
	/**  Lower-case extensions this mapping claims, e.g. `["md", "markdown"]`. */
	extensions?: string[],
	/**  Handler for the default Open action (Enter / double-click). */
	open?: string | null,
	/**  Handler for View (F3, read-only); falls back to `open`. */
	view?: string | null,
	/**  Handler for Edit (F4, read-write); falls back to `open`. */
	edit?: string | null,
};

/**
 *  Target for the viewer's Goto (F5): a 1-based line, an absolute byte offset,
 *  or a percentage through the file.
 */
export type GotoTarget = { kind: "line"; value: number } | { kind: "offset"; value: number } | { kind: "percent"; value: number };

/**
 *  The content of a topic. Tagged the same way as [`OpenOutcome`] so the
 *  generated TypeScript is a discriminated union the renderer can switch on.
 */
export type HelpBody = { kind: "about"; value: AboutBody } | { kind: "shortcuts"; value: ShortcutsBody };

/**
 *  The whole help book: every topic, already rendered and filtered. The frontend
 *  picks one to show and renders it — it makes no decisions about content.
 */
export type HelpBook = {
	topics: HelpTopicView[],
};

/**  One label/value row. */
export type HelpLine = {
	label: string,
	value: string,
};

/**
 *  One outbound link. Opened through the OS browser by the adapter, never
 *  navigated to inside the webview.
 */
export type HelpLink = {
	label: string,
	url: string,
};

/**  One topic, as it appears in the left-hand rail plus the body it renders. */
export type HelpTopicView = {
	/**
	 *  Stable id, e.g. `"about"`. The frontend never switches on it, but it makes
	 *  the payload self-describing and gives a plugin topic a handle.
	 */
	id: string,
	/**  Label for the topic rail. */
	title: string,
	body: HelpBody,
};

/**  Direction for command-history recall (Up / Down at the prompt). */
export type HistoryDir = 
/**  Older — what Up does. */
"prev" | 
/**  Newer, ending back at the line the user was typing. */
"next";

/**
 *  One keybinding: an action id (e.g. `"cursor.down"`) and the key chords bound
 *  to it. Sourced from core config so the webview never hardcodes keys (§6/§7).
 *  Remapping, persistence, and conflict detection are a later slice.
 * 
 *  `context` scopes the binding to the surface that owns the keyboard —
 *  `"panels"`, `"viewer"`, `"editor"`, `"terminal"`, `"help"` — because the same
 *  F-key means different things in each (F4 edits a file from the panels,
 *  toggles hex in the viewer). The frontend groups the keymap by context and
 *  consults the one for whichever surface is on top.
 */
export type KeyBinding = {
	context: string,
	action: string,
	keys: string[],
	/**
	 *  Each chord in `keys`, in the same order, as the user should see it —
	 *  `"⌘S"` on macOS, `"Ctrl+S"` elsewhere. Rendered core-side by
	 *  [`crate::keys::display_chord`] so a renderer painting the F-key bar never
	 *  has to know which platform it is on, or how a chord is spelled
	 *  (CLAUDE.md — the frontend is a thin, swappable layer).
	 */
	labels: string[],
};

/**
 *  Cursor motions — the intents the frontend forwards; the core turns them into
 *  a new cursor index via the single traversal state machine (§5.2).
 */
export type Motion = "up" | "down" | "left" | "right" | "page_up" | "page_down" | "home" | "end";

/**  Target for `navigate`. */
export type NavTarget = 
/**  Enter the directory currently under the cursor. */
{ kind: "into" } | 
/**  Go to the parent, auto-positioning on the folder just exited (§5.2). */
{ kind: "parent" } | 
/**  Jump to an explicit path (absolute or relative). */
{ kind: "path"; value: string };

/**
 *  Where a panel goes when its directory is gone for good and there is nothing to
 *  follow (§5.6).
 */
export type OnLost = 
/**  Walk up to the closest ancestor that still exists and is readable. */
"nearest-ancestor" | 
/**  Go straight to the home directory. */
"home";

/**  A name collision needs a user decision (FAR dialog shapes). */
export type OpCollisionEvent = CollisionPrompt;

/**  An operation finished (success / partial / failed). */
export type OpCompleteEvent = OpOutcome;

/**  An operation failed — rendered as a red-background dialog. */
export type OpErrorEvent = OpErrorInfo;

/**
 *  Payload for the failure event — the frontend renders this as a red-background
 *  dialog. `offer_elevate` gates the OS-native elevation choice (§5.4b / §5.6).
 */
export type OpErrorInfo = {
	op_id: string,
	path: string,
	reason: string,
	offer_elevate: boolean,
};

/**  Copy vs move — the two panel-to-panel transfer operations (§5.4). */
export type OpKind = "copy" | "move";

/**
 *  Structured result of an operation — the frontend renders this, never an
 *  opaque thrown error (§5.6).
 */
export type OpOutcome = {
	op_id: string,
	status: OpStatus,
	summary: string,
};

/**  Progress event payload for a running operation (§5.4a). */
export type OpProgress = {
	op_id: string,
	bytes_done: number,
	bytes_total: number,
	count_done: number,
	count_total: number,
	/**  The file currently being processed. */
	current: string,
};

/**  Progress tick for a running operation. */
export type OpProgressEvent = OpProgress;

/**  Terminal status of an operation (§5.4a / §5.6). */
export type OpStatus = "pending" | "success" | "partial" | "failed" | "cancelled";

/**
 *  How to open a file with an external tool: system default, or the configured
 *  viewer (F3) / editor (F4) for its type (§5.5).
 */
export type OpenAction = "open" | "view" | "edit";

/**
 *  What `open_entry` actually did — the frontend renders the embedded arms and
 *  ignores the external ones (§5.5).
 */
export type OpenOutcome = 
/**  Handed off to an external application; nothing to render. */
{ kind: "launched" } | 
/**  An executable was started; output arrives via the exec events. */
{ kind: "executing" } | 
/**  Nothing to open (`..`, a directory, or an empty panel). */
{ kind: "nothing" } | { kind: "viewer"; value: ViewPage } | { kind: "editor"; value: EditDoc };

/**
 *  Payload for a panel-state change pushed by the core, e.g. the directory
 *  changed underneath us and was refreshed (§5.6).
 */
export type PanelChanged = {
	panel: PanelId,
	state: PanelState,
};

/**  A panel's state changed out of band (e.g. directory changed underneath us). */
export type PanelChangedEvent = PanelChanged;

/**
 *  Layout geometry reported by the frontend on resize / view-mode change. The
 *  cursor state machine needs it to compute the column/page traversal (§5.2) —
 *  the frontend owns pixels, the core owns the resulting cursor index.
 */
export type PanelGeometry = {
	columns: number,
	rows_per_column: number,
};

/**  Which panel an intent targets. The two-panel model is the app's core (§5.1). */
export type PanelId = "left" | "right";

/**
 *  A one-line, non-modal explanation of something that happened to a panel's
 *  directory without the user asking (§5.6). Rendered in the panel footer, not as
 *  a dialog: a background process renaming a folder is not a failure, and the
 *  red-background dialog is reserved for operations that failed.
 */
export type PanelNotice = {
	kind: PanelNoticeKind,
	/**  Ready-to-render sentence, composed by the core. */
	message: string,
	/**  What the notice is about — the directory's previous path, or the volume. */
	path: string,
};

/**
 *  Why a panel is showing an out-of-band notice (§5.6). Drives styling only —
 *  the sentence itself comes from [`PanelNotice::message`], because composing it
 *  needs the old path / volume name and that is core knowledge, not the
 *  frontend's (same split as [`OpErrorInfo::reason`]).
 */
export type PanelNoticeKind = 
/**  The directory was renamed or moved and the panel followed it. */
"moved" | 
/**  Something else now occupies the path; the listing was reloaded fresh. */
"replaced" | 
/**  The directory was deleted; the panel fell back to an ancestor. */
"deleted" | 
/**  The directory was moved to the Trash; the panel fell back to an ancestor. */
"trashed" | 
/**  The volume went away; the panel fell back to home. */
"unmounted" | 
/**
 *  The directory still exists but became unreadable. The panel deliberately
 *  stays put — navigating away would hide the actual problem (§5.6).
 */
"denied";

/**
 *  Persisted per-panel preferences, restored on the next launch (§5.8 / §7).
 * 
 *  Field order matters: TOML requires plain values before tables, and `view_mode`
 *  serializes as a table (`{kind, columns}`), so it comes last. `serde(default)`
 *  lets a hand-edited, partial config still load (§7 — zero-config must work).
 */
export type PanelPrefs = {
	/**  Directory the panel opens to; `None` means a sensible default (e.g. home). */
	start_dir?: string | null,
	sort_mode?: SortMode,
	show_hidden?: boolean,
	view_mode?: ViewMode,
};

/**  The full state of one panel — the unit the frontend renders. */
export type PanelState = {
	path: string,
	entries: Entry[],
	/**  Index into `entries` of the entry under the cursor. */
	cursor_index: number,
	/**
	 *  Index of the first visible entry — the top of the leftmost column. The
	 *  panel scrolls as a sliding window, one entry at a time, rather than
	 *  flipping whole pages (§5.2). Transient: never persisted.
	 */
	top_index: number,
	/**  Indices of selected entries (§5.3). Persists across cursor movement. */
	selection: number[],
	view_mode: ViewMode,
	sort_mode: SortMode,
	show_hidden: boolean,
	geometry: PanelGeometry,
	/**
	 *  The open quick-search box, or `None` when there is none (§5.9). Transient
	 *  like `top_index`: never persisted, and any other input ends it.
	 */
	search: QuickSearch | null,
	/**
	 *  Set when the directory changed underneath the panel and the core had to
	 *  react (§5.6). Transient: cleared by the next deliberate navigation.
	 */
	notice: PanelNotice | null,
};

/**
 *  An open quick-search box on a panel (§5.9).
 * 
 *  The core is the sole author of `query`: a character that matches nothing is
 *  rejected rather than appended, so the string always describes a real entry.
 *  That is why the frontend renders it as text rather than hosting an `<input>` —
 *  a focused field would show the rejected character before the core could
 *  withdraw it.
 */
export type QuickSearch = {
	/**  What the user has typed so far — only characters that matched. */
	query: string,
	/**
	 *  Bumped on every rejected character, so the frontend can beep and flash.
	 *  A counter rather than a flag: two misses in a row must fire twice, and a
	 *  flag that is already `true` would look unchanged.
	 */
	miss_rev: number,
};

/**
 *  Name-collision resolution. FAR shapes: a single-file dialog omits the `*_all`
 *  variants; a multi-file dialog offers all of them (§5.4a).
 */
export type Resolution = "skip" | "skip_all" | "overwrite" | "overwrite_all" | "cancel";

/**
 *  Structured result of an editor save (§5.6 — never an opaque error).
 *  `Conflict` means the file changed on disk since it was opened; the frontend
 *  offers Overwrite (retry with `force`) or Cancel in the red dialog (§5.4b).
 */
export type SaveOutcome = { kind: "saved" } | { kind: "conflict"; value: string } | { kind: "read_only" } | { kind: "failed"; value: string };

/**  Search direction for F7 / Shift+F7. */
export type SearchDirection = "forward" | "backward";

/**  A run of related shortcuts within a section, e.g. "Cursor motion". */
export type ShortcutGroup = {
	category: string,
	title: string,
	items: ShortcutItem[],
};

/**  One shortcut row. */
export type ShortcutItem = {
	/**  The action id, e.g. `"op.copy"` — shown small, and searchable. */
	action: string,
	/**
	 *  **Display** chords (`"⌘⇧T"`, `"↑"`, `"Space"`), not the raw chord strings.
	 *  The renderer never has to know the internal chord format.
	 */
	keys: string[],
	title: string,
	description: string,
};

/**
 *  All shortcuts for one keyboard context (`"panels"`, `"viewer"`, …). The same
 *  key can mean different things in different contexts, which is exactly why the
 *  list is sectioned this way rather than flattened.
 */
export type ShortcutSection = {
	/**  The raw context id from the keymap. */
	context: string,
	/**  Display heading, e.g. `"Panels"`. */
	title: string,
	groups: ShortcutGroup[],
};

/**  The Shortcuts topic: the live keymap, grouped and filtered. */
export type ShortcutsBody = {
	/**
	 *  Echo of the query these results were produced for, so the renderer can
	 *  tell a stale response from a current one.
	 */
	query: string,
	/**
	 *  How many shortcuts survived the filter, and how many exist in total —
	 *  the "12 of 68" counter.
	 */
	match_count: number,
	total_count: number,
	/**  One section per keyboard context that has at least one match. */
	sections: ShortcutSection[],
};

/**  Sort order. Folders-first-by-name is the default (§5.8). */
export type SortMode = "name_folders_first" | "type_name" | "size" | "date";

/**  The whole scrollback, pulled on expand / on mount / after a cap change. */
export type TerminalBuffer = {
	lines: string[],
	pending: string,
};

/**
 *  An incremental scrollback update.
 * 
 *  The core owns the buffer and its eviction policy; this is the delta that
 *  keeps the frontend's mirror exact. Lines rather than bytes, deliberately — a
 *  byte count would be unusable in a frontend that indexes strings in UTF-16
 *  units.
 * 
 *  **Apply it in this order — append, then drop:**
 * 
 *  ```text
 *  lines   = lines.concat(chunk.lines).slice(chunk.dropped)
 *  pending = chunk.pending
 *  ```
 * 
 *  The order is load-bearing, not stylistic. The core appends and *then* trims,
 *  so a single large append can evict lines it just added — feed a 3000-line
 *  burst into a 2 KB buffer and `dropped` exceeds everything the mirror held
 *  beforehand. Dropping first would clamp at zero and leak the surplus, leaving
 *  the mirror permanently longer than the buffer it mirrors.
 */
export type TerminalChunk = {
	/**  Lines completed by this append (no trailing newline). */
	lines: string[],
	/**
	 *  The still-incomplete trailing line; replaces whatever partial the
	 *  frontend was holding.
	 */
	pending: string,
	/**
	 *  Leading lines evicted to stay under the byte cap, counted **after** this
	 *  append — so it can exceed the mirror's previous length.
	 */
	dropped: number,
};

/**
 *  Fresh output from the running command (§5.7). Carries a *line delta* — the
 *  lines completed, the new partial tail, and how many old lines the core
 *  evicted — so the frontend's mirror stays exact without knowing the eviction
 *  policy.
 */
export type TerminalChunkEvent = TerminalChunk;

/**
 *  Embedded-terminal preferences (§7). The scrollback cap is adjustable from the
 *  corner of the expanded pane, and the pane's size is remembered across
 *  restarts the way the panels remember their view state (§5.8).
 */
export type TerminalPrefs = {
	/**  Scrollback cap in bytes — 1 MiB by default (§5.7). */
	scrollback_bytes?: number,
	/**
	 *  Shell used to run commands. `None` means `$SHELL`, falling back to
	 *  `/bin/sh`.
	 */
	shell?: string | null,
	/**
	 *  The pane size to restore on launch. `Full` is deliberately not persisted
	 *  — the Esc curtain is a transient look, not a startup state.
	 */
	size?: TerminalSize,
};

/**
 *  How much room the terminal occupies. Three sizes, two toggles: Cmd+Shift+T
 *  flips `Collapsed` ↔ `Half`, and Esc draws the panels aside as a curtain over
 *  the `Full` terminal (§6) and back again.
 */
export type TerminalSize = 
/**  Just the command line, directly under the panel footers. */
"collapsed" | 
/**  Bottom half of the window: output pane above, command line pinned below. */
"half" | 
/**  Panels hidden entirely — the Esc curtain. */
"full";

/**  The command line's full state — everything the prompt row renders. */
export type TerminalState = {
	/**
	 *  The text in the prompt. Survives losing focus: it is core state, not a
	 *  property of the focused widget (§5.7).
	 */
	input: string,
	/**
	 *  Bumped **only** when the core itself rewrites `input` (history recall,
	 *  Ctrl+Enter insertion, clear, run). The frontend re-seeds its `<input>`
	 *  element on a change and otherwise leaves the user's typing alone, so a
	 *  snapshot arriving mid-keystroke can never clobber it.
	 */
	input_rev: number,
	/**
	 *  Working directory the next command runs in — the active panel's directory
	 *  (§8 Phase 2: the terminal tracks the active panel).
	 */
	cwd: string,
	size: TerminalSize,
	/**  Whether the prompt owns the keyboard (Cmd+T). Drives the accent border. */
	focused: boolean,
	status: TerminalStatus,
	/**  The command line currently executing, if any. */
	running: string | null,
	/**
	 *  Scrollback cap in bytes, configurable from the expanded pane (1 MiB
	 *  default, §5.7).
	 */
	scrollback_bytes: number,
};

/**
 *  The command line's state changed from the backend rather than from a command
 *  the frontend issued — i.e. a run finished, so the indicator must change
 *  colour (§5.7).
 */
export type TerminalStateEvent = TerminalState;

/**
 *  What the run-status indicator at the right edge of the command line shows.
 * 
 *  `Ok`/`Error` are the *last* run's verdict and decay back to `Idle` as soon as
 *  the user touches any control again, so a stale green dot never masquerades as
 *  a fresh result.
 */
export type TerminalStatus = 
/**  Nothing has run since the user last did something — grey, barely visible. */
"idle" | 
/**  A command is running — yellow, flashing. */
"running" | 
/**  Last run exited 0 and wrote nothing to stderr — green. */
"ok" | 
/**  Last run exited non-zero or wrote to stderr — red. */
"error";

/**
 *  Character encoding of a text file. Detected from a BOM or by sniffing;
 *  remembered so the editor writes back what it read.
 */
export type TextEncoding = "utf8" | 
/**  UTF-8 with a byte-order mark, which must be preserved on save. */
"utf8_bom" | "utf16_le" | "utf16_be" | "latin1";

/**  A newer release than the one running, as advertised by the update feed. */
export type UpdateInfo = {
	version: string,
	/**  Release notes from the feed. Often empty; the renderer must cope. */
	notes: string,
};

/**
 *  Per-panel view mode. `Columns(n)` covers the brief multi-column modes
 *  (2 by default); `Detailed` is the single-column-with-metadata mode (§5.2).
 */
export type ViewMode = { kind: "columns"; columns: number } | { kind: "detailed" };

/**
 *  Viewer scroll intents — one offset-advancing state machine, mirroring the
 *  panel cursor's design (§10).
 */
export type ViewMotion = "line_up" | "line_down" | "page_up" | "page_down" | "home" | "end" | "col_left" | "col_right";

/**
 *  One rendered screenful of the viewer. Text and hex modes emit the same shape
 *  — a gutter column plus row strings — so the frontend renders one way and all
 *  formatting stays in the core.
 * 
 *  Position is tracked as a **byte offset**, and `percent` is byte-based, so the
 *  viewer never needs a file's total line count and opens a multi-gigabyte log
 *  instantly (FAR behaviour).
 */
export type ViewPage = {
	id: string,
	path: string,
	name: string,
	mode: ViewerMode,
	wrap: boolean,
	encoding: TextEncoding,
	/**  Line numbers (text) or byte offsets (hex), one per row. */
	gutter: string[],
	rows: string[],
	top_offset: number,
	total_bytes: number,
	/**  Position through the file, 0–100, from `top_offset`. */
	percent: number,
	/**
	 *  1-based logical line at the top of the window, when the index reaches
	 *  that far; `None` in hex mode.
	 */
	top_line: number | null,
	/**  Horizontal scroll, in characters, when wrapping is off. */
	col_offset: number,
	/**
	 *  Whether the file could be written — drives the status line's read-only
	 *  marker and whether F6 (view → edit) can offer an editable buffer.
	 */
	writable: boolean,
};

/**
 *  Which representation the viewer is currently showing. Text and Hex toggle
 *  (F4); Image is fixed for the session.
 */
export type ViewerMode = "text" | "hex" | "image";

/**
 *  Embedded-viewer preferences (§7). `wrap` is toggled with F2 in the viewer and
 *  persisted, matching how the panels persist their view state (§5.8).
 */
export type ViewerPrefs = {
	wrap?: boolean,
	tab_width?: number,
	hex_bytes_per_row?: number,
};

/**
 *  Directory-watching preferences (§5.6 / §7).
 * 
 *  Every value here is a rate or a policy the user may want to change, so none of
 *  it is hardcoded (CLAUDE.md: keybindings and theme values are config-driven —
 *  the same rule applies to anything tunable).
 */
export type WatchPrefs = {
	/**
	 *  Master switch. Off means the panels only refresh on Ctrl+R and after the
	 *  app's own operations, exactly as they did before watching existed.
	 */
	enabled?: boolean,
	/**
	 *  Quiet period before a dirty directory is re-listed. Filesystem events
	 *  arrive in storms; this is what stops one re-list per event.
	 */
	debounce_ms?: number,
	/**
	 *  Upper bound on how long `debounce_ms` may keep deferring. Without it a
	 *  sustained write (an archive extracting into the visible directory) would
	 *  never go quiet and the panel would show nothing until it finished.
	 */
	max_delay_ms?: number,
	/**
	 *  How often to re-check that the panel's directory is still where it was.
	 *  Two syscalls per panel; this is what catches a renamed *ancestor*, which
	 *  produces no event in either watched directory.
	 */
	identity_poll_ms?: number,
	/**
	 *  Follow a renamed or moved directory to its new path. Off falls back to
	 *  treating a move like a deletion.
	 */
	follow_moves?: boolean,
	/**  Where to land when the directory is gone and cannot be followed. */
	on_lost?: OnLost,
	/**
	 *  Poll interval for volumes FSEvents does not cover (SMB/NFS). `0` disables
	 *  watching there entirely, leaving Ctrl+R and the focus refresh.
	 */
	poll_non_local_ms?: number,
	/**
	 *  Re-check both panels when the window regains focus. Cheap, and it covers
	 *  everything the watcher structurally cannot (dropped events, suspension).
	 */
	refresh_on_focus?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

